version: '3.3'

services:
  # API DO WPP
  evolution_api:
    image: atendai/evolution-api:v2.1.1
    container_name: evolution_api
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SERVER_URL=http://localhost:8080
      - API_KEY=MudeEssaSenha123 
      - DATABASE_PROVIDER=local
    volumes:
      - evolution_instances:/evolution/instances
      - evolution_store:/evolution/store

  # BACKEND
  app_garagem:
    build: . 
    container_name: app_garagem
    restart: always
    ports:
      - "8000:8000" # Porta da API
      - "8501:8501" # Porta do Dashboard
    env_file:
      - .env
    volumes:
      - .:/app # Sincronia em tempo real
    depends_on:
      - evolution_api

volumes:
  evolution_instances:
  evolution_store: